name: difference_editor
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  # State Management
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

  # Image
  image_picker: ^1.0.4

  # JSON Serialization
  json_annotation: ^4.8.1

  # Others
  path: ^1.8.3
  uuid: ^4.2.1
  path_provider: ^2.1.1
  file_picker: ^8.0.0+1
  vector_math: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  build_runner: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
